services:
  leo-kernel:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ros
        USER_UID: 1000
    image: leo-kernel
    container_name: leo-kernel
    network_mode: host
    ipc: host
    volumes:
      - ./src:/home/ros/ws/src:rw
    command: sleep infinity
